name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Ensure this is the latest version

    - name: Set up JDK 11
      uses: actions/setup-java@v3  # Ensure this is the latest version
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Cache Gradle packages
      uses: actions/cache@v3  # Ensure this is the latest version
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Run tests
      run: ./gradlew test  # Optional: Run tests if you have them

    - name: Upload APK
      uses: actions/upload-artifact@v3  # Ensure this is the latest version
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
